"""Aggregate every ``verdict.json`` under verification/ into SUCCESS_MATRIX.md.

This script does NO physics: it reads the recorded per-case verdicts and emits
the master success matrix. Re-run it whenever a case's verdict.json changes.

    python verification/build_success_matrix.py
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from _compare_lib import VERDICT_BADGE, VERDICT_ORDER, read_verdict  # noqa: E402

CATEGORIES = [
    ("neutralCurve_verification", "Neutral curves"),
    ("growthRate_verification", "Growth rates"),
    ("eigenvalueAnchor_verification", "Eigenvalue anchors"),
]


def _cond(c: dict) -> str:
    bits = []
    if "Ma" in c:
        ma = c["Ma"]
        bits.append(f"M={ma:g}" if isinstance(ma, (int, float)) else f"M={ma}")
    psi = c.get("psi_deg")
    if psi is not None:
        bits.append(f"ψ={psi:g}°" if isinstance(psi, (int, float)) else f"ψ={psi}°")
    if c.get("gas"):
        bits.append(str(c["gas"]))
    if c.get("wall"):
        bits.append(str(c["wall"]))
    return ", ".join(bits)


def _pct(x):
    return f"{100 * float(x):.1f}%"


def _headline(v: dict) -> str:
    """One-line curated metric per case (full numbers live in verdict.json)."""
    m = v.get("metrics", {})
    if not m:
        return "—"
    # Mack growth-rate cases
    if "curve_median_rel_err" in m:
        s = f"curve median {_pct(m['curve_median_rel_err'])}"
        if "table_anchor_rel_err" in m:
            s += f"; Table-10.1 anchor {_pct(m['table_anchor_rel_err'])}"
        return s
    # Özgen neutral-curve cases
    if "median_rel_err_alpha" in m:
        topo = "closed-arch" if m.get("topology_ok") else "open-lobe"
        return f"median |Δα|/α {_pct(m['median_rel_err_alpha'])}; topology {topo}"
    # Eigenvalue-anchor cases (Malik 1990 etc.)
    if "alpha_r_rel_err" in m:
        return (f"α_r {_pct(m['alpha_r_rel_err'])}, "
                f"α_i {_pct(m['alpha_i_rel_err'])} (N={m.get('N', '?')})")
    if "malik_omega" in m:
        o = m["malik_omega"]
        return f"Malik ω={o[0]:.4f}{o[1]:+.5f}i (temporal; no pyMack run)"
    # Ma & Zhong second-mode neutral-branch Reynolds numbers (R = sqrt(Re_x))
    if "branch_I_rel_err" in m and "branch_II_rel_err" in m:
        topo = "closed band" if m.get("topology_ok") else "topology mismatch"
        return (f"Branch I R {m['branch_I_R_pymack']:g} ({_pct(m['branch_I_rel_err'])}), "
                f"Branch II R {m['branch_II_R_pymack']:g} ({_pct(m['branch_II_rel_err'])}); "
                f"{topo}")
    # Sean dimensional neutral curve
    if "upper_branch_MAE_mm_200_600kHz" in m:
        return (f"upper {m['upper_branch_MAE_mm_200_600kHz']:.1f} mm; "
                f"lower {m.get('lower_branch_MAE_mm_330_600kHz', float('nan')):.1f} mm "
                "(gated bands)")
    # Fallback: first two scalar metrics
    parts = [f"{k}={val:.3g}" for k, val in m.items()
             if isinstance(val, (int, float))][:2]
    return "; ".join(parts) if parts else "—"


def _first_sentence(text: str) -> str:
    text = text.replace("\n", " ").strip()
    for end in (". ", "; "):
        i = text.find(end)
        if 0 < i < 200:
            return text[: i + 1].strip()
    return text[:200]


def main() -> int:
    rows_by_cat: dict[str, list[dict]] = {}
    for sub, _ in CATEGORIES:
        cases = []
        cat_dir = HERE / sub
        if cat_dir.is_dir():
            for vf in sorted(cat_dir.glob("*/verdict.json")):
                cases.append(read_verdict(vf))
        cases.sort(key=lambda v: (VERDICT_ORDER.get(v.get("verdict", "pending"), 9),
                                  v.get("case_id", "")))
        rows_by_cat[sub] = cases

    tally = {"agrees": 0, "acceptable": 0, "disagrees": 0, "pending": 0}
    for cases in rows_by_cat.values():
        for v in cases:
            tally[v.get("verdict", "pending")] = tally.get(v.get("verdict", "pending"), 0) + 1

    lines = []
    lines.append("# pyMack Verification Success Matrix")
    lines.append("")
    lines.append("Honest agreement audit of pyMack against published / external")
    lines.append("benchmarks at their **exact** conditions. Generated by")
    lines.append("`verification/build_success_matrix.py` from per-case `verdict.json`.")
    lines.append("Thresholds and methodology: `verification/README.md`.")
    lines.append("")
    total = sum(tally.values())
    lines.append(
        f"**Tally ({total} cases):** "
        f"{VERDICT_BADGE['agrees']} {tally['agrees']} · "
        f"{VERDICT_BADGE['acceptable']} {tally['acceptable']} · "
        f"{VERDICT_BADGE['disagrees']} {tally['disagrees']} · "
        f"{VERDICT_BADGE['pending']} {tally['pending']}"
    )
    lines.append("")

    for sub, title in CATEGORIES:
        cases = rows_by_cat.get(sub, [])
        lines.append(f"## {title}")
        lines.append("")
        if not cases:
            lines.append("_No cases yet._")
            lines.append("")
            continue
        lines.append("| Case | Source | Conditions | Verdict | Headline |")
        lines.append("|---|---|---|---|---|")
        for v in cases:
            lines.append(
                "| `{cid}` | {src} | {cond} | {verd} | {head} |".format(
                    cid=v.get("case_id", "?"),
                    src=v.get("source", "?").split(",")[0],
                    cond=_cond(v.get("conditions", {})),
                    verd=VERDICT_BADGE.get(v.get("verdict", "pending"), "?"),
                    head=_headline(v),
                )
            )
        lines.append("")

    # Per-case detail (full reasoning; the table stays scannable).
    lines.append("## Details")
    lines.append("")
    for sub, _ in CATEGORIES:
        for v in rows_by_cat.get(sub, []):
            reason = v.get("verdict_reason", "").strip()
            if not reason or v.get("verdict") == "pending":
                continue
            lines.append(
                f"**`{v['case_id']}`** — {VERDICT_BADGE.get(v.get('verdict'), '?')} "
                f"({v.get('quantity', '')})  "
            )
            lines.append("")
            lines.append(reason)
            lines.append("")

    out = HERE / "SUCCESS_MATRIX.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}  ({total} cases: {tally})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
